const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const get=(k,f)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f));
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const escapeText=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const templates=[
  ["Beginner full body","Squats · Push-Ups · Plank · 3 rounds"],["5K preparation","Easy run · mobility · 3 sessions/week"],["Home strength","Push · squat · lunge · core"],["Yoga recovery","Gentle flow · breathing · 15 minutes"],["Adaptive upper body","Seated push · band row · mobility"]
];
const library=[
  ["Meditation","No equipment","Breathing, body scan and recovery."],["Mobility","Mat","Controlled joint range and gentle movement."],["Para-athlete strength","Chair / band","Adaptive seated strength and mobility options."],["Cricket bowling","Open space","Technique guidance; no automatic score yet."],["Football kick","Ball","Technique guide; no automatic score yet."],["Badminton / tennis","Racket","Movement preparation and safety cues."]
];
function panel(title,body,subtitle=''){return `<section class="panel local-tools"><div class="panel-heading"><div><h2>${title}</h2>${subtitle?`<p class="muted">${subtitle}</p>`:''}</div></div>${body}</section>`;}
function inject(){
  q('#home .library').insertAdjacentHTML('afterend',panel('Training plans & activity library',`<div class="tool-grid"><article class="tool-card"><h3>Workout templates</h3><p class="muted">Choose a plan to add it to today’s training.</p><div id="templateList" class="template-list"></div></article><article class="tool-card"><h3>Equipment filter</h3><p class="muted">Choose a filter, then select an activity to see its guide.</p><div id="equipmentChips" class="chips"><button class="active" data-equipment="All">All</button><button data-equipment="No equipment">Bodyweight</button><button data-equipment="Mat">Mat</button><button data-equipment="Chair / band">Adaptive</button></div><div id="resourceList" class="resource-list"></div></article><article class="tool-card wide"><h3>Today’s plan</h3><div id="todayPlan" class="template-item"><span>Choose a workout template to build today’s session.</span></div><p id="adaptiveSuggestion" class="feedback"></p></article></div>`,'Build a routine that fits your day.'));
  q('#nutrition').insertAdjacentHTML('beforeend',panel('Recovery & meditation',`<div class="tool-grid"><article class="tool-card"><h3>Box breathing</h3><div id="breathOrb" class="breath-orb">Ready</div><p id="breathText" class="muted">4 seconds in · hold · out · hold.</p><div class="tool-actions"><button id="breathButton" class="button primary">Start breathing</button><button id="restDayButton" class="button secondary">Plan recovery day</button></div><p id="recoveryFeedback" class="feedback"></p></article><article class="tool-card"><h3>Safety preferences</h3><label>Sensitive area / condition<input id="safetyArea" placeholder="Example: knee discomfort"></label><label>Comfort note<textarea id="safetyNote" rows="3" placeholder="Keep this non-medical; stop if there is pain."></textarea></label><div class="tool-actions"><button id="saveSafety" class="button secondary">Save preferences</button></div><p id="safetyFeedback" class="feedback"></p></article></div>`));
  q('#progress').insertAdjacentHTML('beforeend',panel('Measurements, preferences & app tools',`<div class="tool-grid"><article class="tool-card"><h3>Body measurements</h3><form id="measurementForm"><div class="tool-grid"><label>Weight (kg)<input id="measureWeight" type="number" step=".1"></label><label>Waist (cm)<input id="measureWaist" type="number" step=".1"></label></div><div class="tool-actions"><button class="button primary">Save measurement</button></div></form><div id="measurementList" class="measurement-list"></div></article><article class="tool-card"><h3>Photo journal</h3><label>Add a before/after photo<input id="photoInput" type="file" accept="image/*"></label><p class="muted">Keep up to two photos to compare your progress.</p><div id="photoJournal" class="photo-journal"></div></article><article class="tool-card"><h3>Appearance & accessibility</h3><div class="access-row"><span>Accent colour</span><input id="accentPicker" type="color" value="#ff632e"></div><div class="access-row"><span>High contrast</span><input id="contrastToggle" type="checkbox"></div><div class="access-row"><span>Compact layout</span><input id="compactToggle" type="checkbox"></div><div class="access-row"><span>Timer sounds</span><input id="soundToggle" type="checkbox" checked></div></article><article class="tool-card"><h3>App health</h3><div id="systemHealth" class="system-grid"></div><p class="muted">Camera and GPS are checked when you start using them.</p></article><article class="tool-card"><h3>Import & print</h3><label>Import workout CSV<input id="csvImport" type="file" accept=".csv,text/csv"></label><div class="tool-actions"><button id="printPlan" class="button secondary">Print weekly plan</button><button id="showTour" class="button secondary">Show app tour</button></div><p id="importFeedback" class="feedback"></p></article></div>`));
  document.body.insertAdjacentHTML('beforeend',`<div id="onboarding" class="onboarding" hidden><section class="onboarding-card"><p class="kicker">WELCOME TO VISTA</p><h2>Your training, all in one place.</h2><ol><li>Create or update your profile.</li><li>Use Track to record a route or Workout to review your movement.</li><li>Build plans, set reminders and save your progress.</li><li>Use Backup whenever you want a copy of your progress.</li></ol><button id="closeTour" class="button primary">Start using VISTA</button></section></div>`);
}
const templateExercises=['Squats','Running','Push-Ups','Yoga Flow','Para-athlete strength'];
const resourceExercises={Meditation:'Meditation',Mobility:'Yoga Flow','Para-athlete strength':'Para-athlete strength','Cricket bowling':'Cricket bowling','Football kick':'Football kick','Badminton / tennis':'Badminton / tennis'};
function selectExercise(name){window.dispatchEvent(new CustomEvent('vista:select-exercise',{detail:name}));}
function renderTemplates(){q('#templateList').innerHTML=templates.map(([name,desc],index)=>`<button class="template-item template-select" data-template="${index}"><b>${name}</b><span>${desc}</span></button>`).join('');qa('.template-select').forEach(button=>button.onclick=()=>{const index=+button.dataset.template,item=templates[index];put('vista-today-template',{name:item[0],desc:item[1],exercise:templateExercises[index],date:new Date().toISOString()});renderTodayPlan();});}
function renderTodayPlan(){const value=get('vista-today-template',null),plan=q('#todayPlan');plan.innerHTML=value?`<div><b>${escapeText(value.name)}</b><br><span>${escapeText(value.desc)}</span></div><div class="tool-actions"><button id="startTodayPlan" class="button primary">Start workout</button><button id="clearTodayPlan" class="button secondary">Remove</button></div>`:`<span>Choose a workout template to build today’s session.</span>`;q('#startTodayPlan')?.addEventListener('click',()=>selectExercise(value.exercise||'Push-Ups'));q('#clearTodayPlan')?.addEventListener('click',()=>{localStorage.removeItem('vista-today-template');renderTodayPlan();});const history=get('vista-history',[]).filter(item=>Number.isFinite(item.score)),suggestion=q('#adaptiveSuggestion');if(!history.length)suggestion.textContent='Complete a supported form review to receive a training suggestion here.';else{const recent=history.slice(0,3),average=recent.reduce((sum,item)=>sum+item.score,0)/recent.length;suggestion.textContent=average<65?'Try the same movement at a slower pace and focus on keeping your full body in frame.':average<80?'Your form is progressing well. Repeat the plan and aim for smoother, more even reps.':'Your form is looking consistent. Add one small progression only if it still feels comfortable.';}}
function renderResources(filter='All'){q('#resourceList').innerHTML=library.filter(item=>filter==='All'||item[1]===filter).map(item=>`<button class="resource-item resource-select" data-resource="${escapeText(item[0])}"><b>${item[0]}</b><small>${item[2]}</small></button>`).join('')||'<p class="muted">No activities match this filter yet.</p>';qa('.resource-select').forEach(button=>button.onclick=()=>{const name=button.dataset.resource;if(name==='Meditation'){q('[data-nav="nutrition"]')?.click();setTimeout(()=>q('#breathOrb')?.scrollIntoView({behavior:'smooth',block:'center'}),120);return;}selectExercise(resourceExercises[name]||name);});}
function breathSound(stage){if(!get('vista-local-ui',{sound:true}).sound)return;try{const audio=new (window.AudioContext||window.webkitAudioContext)(),oscillator=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;oscillator.type='sine';const tones={Inhale:[246,392],Hold:[330,330],Exhale:[392,196]}[stage]||[280,280];oscillator.frequency.setValueAtTime(tones[0],now);oscillator.frequency.exponentialRampToValueAtTime(tones[1],now+.55);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.035,now+.08);gain.gain.exponentialRampToValueAtTime(.0001,now+.65);oscillator.connect(gain).connect(audio.destination);oscillator.start(now);oscillator.stop(now+.7);}catch{}}
function setupBreathing(){let id=null,phase=0;const phases=[['Inhale','inhale'],['Hold','hold'],['Exhale','exhale'],['Hold','hold']];q('#breathButton').onclick=()=>{if(id){clearInterval(id);id=null;q('#breathButton').textContent='Start breathing';q('#breathOrb').className='breath-orb';q('#breathOrb').textContent='Ready';q('#breathText').textContent='4 seconds in · hold · out · hold.';return;}phase=0;q('#breathButton').textContent='Stop breathing';const next=()=>{const [text,className]=phases[phase++%phases.length],orb=q('#breathOrb');orb.textContent=text;orb.className=`breath-orb ${className}`;q('#breathText').textContent=`${text} gently for 4 seconds.`;breathSound(text);};next();id=setInterval(next,4000);};q('#restDayButton').onclick=()=>{const days=get('vista-recovery-days',[]);days.unshift(new Date().toISOString());put('vista-recovery-days',days.slice(0,30));q('#recoveryFeedback').textContent='Recovery day recorded. Try gentle mobility, breathing and hydration.';};}
function setupSafety(){const saved=get('vista-safety',{});q('#safetyArea').value=saved.area||'';q('#safetyNote').value=saved.note||'';q('#saveSafety').onclick=()=>{put('vista-safety',{area:q('#safetyArea').value.trim(),note:q('#safetyNote').value.trim()});q('#safetyFeedback').textContent='Preferences saved. VISTA does not replace professional medical advice.';};}
function renderMeasurements(){const values=get('vista-measurements',[]);q('#measurementList').innerHTML=values.length?values.slice(0,8).map(value=>`<div class="measurement-row"><div><b>${value.weight||'—'} kg</b><br><small>Waist: ${value.waist||'—'} cm · ${new Date(value.date).toLocaleDateString()}</small></div></div>`).join(''):'<p class="muted">No measurements saved.</p>';}
function setupMeasurements(){q('#measurementForm').onsubmit=event=>{event.preventDefault();const values=get('vista-measurements',[]);values.unshift({weight:Number(q('#measureWeight').value)||null,waist:Number(q('#measureWaist').value)||null,date:new Date().toISOString()});put('vista-measurements',values.slice(0,100));q('#measurementForm').reset();renderMeasurements();};}
function renderPhotos(){const photos=get('vista-photo-journal',[]),box=q('#photoJournal');box.innerHTML=photos.length?photos.map((photo,index)=>`<figure><img src="${photo.data}" alt="Fitness journal photo"><figcaption>${new Date(photo.date).toLocaleDateString()} <button data-photo="${index}" class="text-button">Remove</button></figcaption></figure>`).join(''):'<p class="muted">Add a photo when you want to track visual progress.</p>';qa('[data-photo]').forEach(button=>button.onclick=()=>{const photos=get('vista-photo-journal',[]);photos.splice(+button.dataset.photo,1);put('vista-photo-journal',photos);renderPhotos();});}
function setupPhotos(){q('#photoInput').onchange=event=>{const file=event.target.files?.[0];if(!file)return;const image=new Image(),reader=new FileReader();reader.onload=()=>{image.onload=()=>{const max=480,ratio=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*ratio);canvas.height=Math.round(image.height*ratio);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);try{const photos=get('vista-photo-journal',[]);photos.unshift({data:canvas.toDataURL('image/jpeg',.68),date:new Date().toISOString()});put('vista-photo-journal',photos.slice(0,2));renderPhotos();}catch{alert('There is not enough space for another photo. Remove an existing photo and try again.');}};image.src=reader.result;};reader.readAsDataURL(file);};}
function setupAppearance(){const settings=get('vista-local-ui',{accent:'#ff632e',contrast:false,compact:false,sound:true});const apply=()=>{document.documentElement.style.setProperty('--orange',settings.accent);document.body.classList.toggle('high-contrast',settings.contrast);document.body.classList.toggle('compact-layout',settings.compact);put('vista-local-ui',settings);};q('#accentPicker').value=settings.accent;q('#contrastToggle').checked=settings.contrast;q('#compactToggle').checked=settings.compact;q('#soundToggle').checked=settings.sound;apply();q('#accentPicker').oninput=e=>{settings.accent=e.target.value;apply();};q('#contrastToggle').onchange=e=>{settings.contrast=e.target.checked;apply();};q('#compactToggle').onchange=e=>{settings.compact=e.target.checked;apply();};q('#soundToggle').onchange=e=>{settings.sound=e.target.checked;apply();};}
function renderHealth(){const profile=!!get('vista-profile',null),online=navigator.onLine,storage=localStorage.getItem('vista-history')?'Ready':'New';q('#systemHealth').innerHTML=`<div><small>CONNECTION</small><b>${online?'Online':'Offline'}</b></div><div><small>PROFILE</small><b>${profile?'Ready':'Missing'}</b></div><div><small>PROGRESS</small><b>${storage}</b></div>`;}
function setupUtilities(){q('#csvImport').onchange=event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const rows=String(reader.result).trim().split(/\r?\n/);if(rows.length<2){q('#importFeedback').textContent='The CSV needs a header and at least one data row.';return;}const history=get('vista-history',[]);rows.slice(1).forEach(row=>{const cols=row.split(',').map(x=>x.replace(/^"|"$/g,'').trim());if(cols[1])history.push({id:crypto.randomUUID(),date:new Date().toISOString(),exercise:cols[1],selectedExercise:cols[1],score:null,reps:Number(cols[5])||0,goodReps:0,consistency:null,duration:Number(cols[8])||0,metrics:{'Import':'CSV'},findings:['Imported workout record.'],recommendations:[]});});put('vista-history',history.slice(-100));q('#importFeedback').textContent=`Imported ${rows.length-1} workout row(s). Open Progress to view them.`;};reader.readAsText(file);};q('#printPlan').onclick=()=>window.print();q('#showTour').onclick=()=>q('#onboarding').hidden=false;q('#closeTour').onclick=()=>{q('#onboarding').hidden=true;localStorage.setItem('vista-tour-complete','true');};if(!localStorage.getItem('vista-tour-complete'))setTimeout(()=>q('#onboarding').hidden=false,1200);}
function shortcuts(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const key=event.key.toLowerCase();if(key==='a')q('[data-nav="workout"]')?.click();if(key==='t')q('#themeToggle')?.click();if(key==='r')q('#resetLiveButton')?.click();if(key===' ') {event.preventDefault();q('#liveAnalyzeButton')?.click();}}
inject();renderTemplates();renderTodayPlan();renderResources();qa('#equipmentChips button').forEach(button=>button.onclick=()=>{qa('#equipmentChips button').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderResources(button.dataset.equipment);});setupBreathing();setupSafety();setupMeasurements();renderMeasurements();setupPhotos();renderPhotos();setupAppearance();renderHealth();setupUtilities();document.addEventListener('keydown',shortcuts);window.addEventListener('online',renderHealth);window.addEventListener('offline',renderHealth);
